language: cpp
os:
  - linux
compiler:
  - gcc
notifications:
  email:
    on_success: always
    on_failure: always
cache:
  - ccache
env:
  - NODE_LABELS="Linux Ubuntu Ubuntu-12.04"
before_install:
  - travis_retry sudo apt-get install -qq ccache
script:
  - export CXX="ccache $CXX"
  - ./.jenkins
